### ISSUE TITLE
Add .idea folder to .gitignore

### ISSUE THREAD

**Issue by Dcruise546** [Jyotsna-Shetty/VehicleInfoCheck#3]
From what I could understand, the .idea folder remains stagnant across all the commits. If it has not been modified by any of your team members and if it seems to be automatically generated by your Android studio, then please add this folder as a part of .gitignore.

Forget not to check the functionality before committing it!

**Comment by Jyotsna-Shetty** [comment]
Yes, the .idea folder has not been modified since the first commit. After going through the contents of the folder, I added it to .gitignore.
